# Generated by Django 2.1.5 on 2019-03-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedproducts',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
