# Generated by Django 2.1.5 on 2019-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0002_ownedproducts_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='ownedproducts',
            name='product',
            field=models.ManyToManyField(to='substitut.Products'),
        ),
    ]
