# Generated by Django 2.1.5 on 2019-03-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0004_auto_20190326_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='ownedproducts',
            name='product',
            field=models.ManyToManyField(default='', to='substitut.Products'),
        ),
    ]
