# Generated by Django 2.1.5 on 2019-03-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0005_auto_20190327_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='ownedproducts',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='substitut.Products'),
        ),
    ]
