# Generated by Django 2.1.5 on 2019-03-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0006_auto_20190327_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='substitut.Users')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='substitut.Products')),
            ],
        ),
        migrations.RemoveField(
            model_name='ownedproducts',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='ownedproducts',
            name='product',
        ),
        migrations.DeleteModel(
            name='OwnedProducts',
        ),
    ]
