# Generated by Django 2.1.5 on 2019-03-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0008_auto_20190327_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedproducts',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='ownedproducts',
            name='product',
        ),
        migrations.DeleteModel(
            name='OwnedProducts',
        ),
    ]
