# Generated by Django 2.1.5 on 2019-03-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0009_auto_20190327_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitut.Users')),
                ('saved_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitut.Products')),
            ],
        ),
    ]
