# Generated by Django 2.1.7 on 2019-03-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0011_saving_saved_product_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='saved_product_key',
            field=models.CharField(max_length=100),
        ),
    ]
