# Generated by Django 2.1.7 on 2019-03-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0013_auto_20190329_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='saved_product_key',
        ),
    ]
