# Generated by Django 2.1.7 on 2019-03-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0014_remove_saving_saved_product_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='product_key',
            field=models.CharField(default='', max_length=9000),
        ),
    ]
