# Generated by Django 2.1.7 on 2019-03-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0015_saving_product_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='saving',
            name='saved_product',
        ),
        migrations.AlterField(
            model_name='saving',
            name='contact',
            field=models.CharField(default='', max_length=100),
        ),
    ]
