# Generated by Django 2.1.7 on 2019-04-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0016_auto_20190331_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
