# Generated by Django 2.1.7 on 2019-04-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0017_auto_20190408_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
