# Generated by Django 2.1.7 on 2019-04-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0018_auto_20190408_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
