# Generated by Django 2.1.7 on 2019-04-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0019_productscategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsCategories',
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name']},
        ),
    ]
