# Generated by Django 2.1.7 on 2019-04-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0020_auto_20190409_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['category']},
        ),
    ]
