# Generated by Django 2.1.7 on 2019-04-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0021_auto_20190409_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
