# Generated by Django 2.1.7 on 2019-04-15 10:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitut', '0034_auto_20190415_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=900), default=list, null=True, size=1),
        ),
    ]
